image: rocker/verse:3.6.2

pages:
  stage: deploy
  script:
    - cd ..
    - R CMD build maxsim
    - mkdir maxsim/public
    - mv maxsim_0.0.1.tar.gz maxsim/public/
  artifacts:
    paths:
      - public
  only:
    - master
