image: rocker/verse:3.6.2

stages:
  - build
  - test
  - deploy

binary:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y libgsl-dev
    - apt-get install -y libmpfr-dev
    - apt-get install -y python3-pip
    - apt-get install -y libpython3-dev
    - pip3 install virtualenv
    - r -e 'install.packages("philentropy")'
    - r -e 'install.packages("BTM")'
    - r -e 'devtools::install_github("herreio/maxplanckr")'
    - r -e 'devtools::install_github("herreio/topmodelr")'
  script:
    - r -e 'devtools::build(binary = TRUE)'

install:
  stage: test
  script:
    - r -e 'devtools::install()'

pages:
  stage: deploy
  script:
    - ls -l .
    - ls -l ..
    - cd ..
    - R CMD build maxsim
    - R CMD install maxsim_0.0.1.tar.gz
    - mkdir maxsim/public
    - mv maxsim_0.0.1.tar.gz maxsim/public/
  artifacts:
    paths:
      - public
  only:
    - master
