image: rocker/verse:3.6.2

pages:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y tree
  script:
    - cd ..
    - R CMD build maxsim
    - mkdir maxsim/public
    - mv maxsim_0.0.1.tar.gz maxsim/public/
    - R CMD Rd2pdf maxsim
    - mv maxsim.pdf maxsim/public/
    - cd maxsim/public
    - tree . > ../tree.txt
    - echo "<html><body><pre>" > index.html
    - cat ../tree.txt >> index.html
    - echo "</pre></body></html>" >> index.html
    - rm ../tree.txt
  artifacts:
    paths:
      - public
  only:
    - master
